Enhance github actions worklfow file

diff --git a/.github/workflows/generate_localization.yml b/.github/workflows/generate_localization.yml
--- a/.github/workflows/generate_localization.yml
+++ b/.github/workflows/generate_localization.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - main
+    paths:
+      - '.github/workflows/generate_localization.yml'
 
 permissions:
   contents: write
@@ -17,6 +19,7 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
+        token: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Install SwiftGen
       run: |
@@ -24,7 +27,8 @@ jobs:
 
     - name: Run SwiftGen
       run: |
-        swiftgen config run
+        swiftgen config run .
+        git status
 
     - name: Configure Git
       run: |
@@ -33,8 +37,12 @@ jobs:
 
     - name: Commit and push changes
       run: |
-        git add Sources/CasaZurigol10n/Generated
-        git diff --quiet || git commit -m 'generated localization file'
-        git push origin main
+        git add -A
+        if git diff --staged --quiet; then
+          echo "No changes to commit"
+        else
+          git commit -m "Generated localization file"
+          git push origin main || (echo "Push failed" && exit 1)
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
